package com.test.model;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table test
 *
 * @mbg.generated Sun Jul 15 12:12:25 CST 2018
 */
public class Test {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.idtest
     *
     * @mbg.generated Sun Jul 15 12:12:25 CST 2018
     */
    private Integer idtest;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.testcol
     *
     * @mbg.generated Sun Jul 15 12:12:25 CST 2018
     */
    private String testcol;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.testcol1
     *
     * @mbg.generated Sun Jul 15 12:12:25 CST 2018
     */
    private String testcol1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.testcol2
     *
     * @mbg.generated Sun Jul 15 12:12:25 CST 2018
     */
    private String testcol2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.testcol3
     *
     * @mbg.generated Sun Jul 15 12:12:25 CST 2018
     */
    private String testcol3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.testcol4
     *
     * @mbg.generated Sun Jul 15 12:12:25 CST 2018
     */
    private String testcol4;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.idtest
     *
     * @return the value of test.idtest
     *
     * @mbg.generated Sun Jul 15 12:12:25 CST 2018
     */
    public Integer getIdtest() {
        return idtest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.idtest
     *
     * @param idtest the value for test.idtest
     *
     * @mbg.generated Sun Jul 15 12:12:25 CST 2018
     */
    public void setIdtest(Integer idtest) {
        this.idtest = idtest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.testcol
     *
     * @return the value of test.testcol
     *
     * @mbg.generated Sun Jul 15 12:12:25 CST 2018
     */
    public String getTestcol() {
        return testcol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.testcol
     *
     * @param testcol the value for test.testcol
     *
     * @mbg.generated Sun Jul 15 12:12:25 CST 2018
     */
    public void setTestcol(String testcol) {
        this.testcol = testcol == null ? null : testcol.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.testcol1
     *
     * @return the value of test.testcol1
     *
     * @mbg.generated Sun Jul 15 12:12:25 CST 2018
     */
    public String getTestcol1() {
        return testcol1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.testcol1
     *
     * @param testcol1 the value for test.testcol1
     *
     * @mbg.generated Sun Jul 15 12:12:25 CST 2018
     */
    public void setTestcol1(String testcol1) {
        this.testcol1 = testcol1 == null ? null : testcol1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.testcol2
     *
     * @return the value of test.testcol2
     *
     * @mbg.generated Sun Jul 15 12:12:25 CST 2018
     */
    public String getTestcol2() {
        return testcol2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.testcol2
     *
     * @param testcol2 the value for test.testcol2
     *
     * @mbg.generated Sun Jul 15 12:12:25 CST 2018
     */
    public void setTestcol2(String testcol2) {
        this.testcol2 = testcol2 == null ? null : testcol2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.testcol3
     *
     * @return the value of test.testcol3
     *
     * @mbg.generated Sun Jul 15 12:12:25 CST 2018
     */
    public String getTestcol3() {
        return testcol3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.testcol3
     *
     * @param testcol3 the value for test.testcol3
     *
     * @mbg.generated Sun Jul 15 12:12:25 CST 2018
     */
    public void setTestcol3(String testcol3) {
        this.testcol3 = testcol3 == null ? null : testcol3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.testcol4
     *
     * @return the value of test.testcol4
     *
     * @mbg.generated Sun Jul 15 12:12:25 CST 2018
     */
    public String getTestcol4() {
        return testcol4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.testcol4
     *
     * @param testcol4 the value for test.testcol4
     *
     * @mbg.generated Sun Jul 15 12:12:25 CST 2018
     */
    public void setTestcol4(String testcol4) {
        this.testcol4 = testcol4 == null ? null : testcol4.trim();
    }
}