package com.test.model;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table user
 *
 * @mbg.generated Sun Jul 15 12:12:25 CST 2018
 */
public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbg.generated Sun Jul 15 12:12:25 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.usercol
     *
     * @mbg.generated Sun Jul 15 12:12:25 CST 2018
     */
    private String usercol;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.usercol1
     *
     * @mbg.generated Sun Jul 15 12:12:25 CST 2018
     */
    private String usercol1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.usercol2
     *
     * @mbg.generated Sun Jul 15 12:12:25 CST 2018
     */
    private String usercol2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.usercol3
     *
     * @mbg.generated Sun Jul 15 12:12:25 CST 2018
     */
    private String usercol3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.usercol4
     *
     * @mbg.generated Sun Jul 15 12:12:25 CST 2018
     */
    private String usercol4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.usercol5
     *
     * @mbg.generated Sun Jul 15 12:12:25 CST 2018
     */
    private String usercol5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.usercol6
     *
     * @mbg.generated Sun Jul 15 12:12:25 CST 2018
     */
    private String usercol6;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.usercol7
     *
     * @mbg.generated Sun Jul 15 12:12:25 CST 2018
     */
    private String usercol7;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.usercol8
     *
     * @mbg.generated Sun Jul 15 12:12:25 CST 2018
     */
    private String usercol8;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbg.generated Sun Jul 15 12:12:25 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbg.generated Sun Jul 15 12:12:25 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.usercol
     *
     * @return the value of user.usercol
     *
     * @mbg.generated Sun Jul 15 12:12:25 CST 2018
     */
    public String getUsercol() {
        return usercol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.usercol
     *
     * @param usercol the value for user.usercol
     *
     * @mbg.generated Sun Jul 15 12:12:25 CST 2018
     */
    public void setUsercol(String usercol) {
        this.usercol = usercol == null ? null : usercol.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.usercol1
     *
     * @return the value of user.usercol1
     *
     * @mbg.generated Sun Jul 15 12:12:25 CST 2018
     */
    public String getUsercol1() {
        return usercol1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.usercol1
     *
     * @param usercol1 the value for user.usercol1
     *
     * @mbg.generated Sun Jul 15 12:12:25 CST 2018
     */
    public void setUsercol1(String usercol1) {
        this.usercol1 = usercol1 == null ? null : usercol1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.usercol2
     *
     * @return the value of user.usercol2
     *
     * @mbg.generated Sun Jul 15 12:12:25 CST 2018
     */
    public String getUsercol2() {
        return usercol2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.usercol2
     *
     * @param usercol2 the value for user.usercol2
     *
     * @mbg.generated Sun Jul 15 12:12:25 CST 2018
     */
    public void setUsercol2(String usercol2) {
        this.usercol2 = usercol2 == null ? null : usercol2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.usercol3
     *
     * @return the value of user.usercol3
     *
     * @mbg.generated Sun Jul 15 12:12:25 CST 2018
     */
    public String getUsercol3() {
        return usercol3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.usercol3
     *
     * @param usercol3 the value for user.usercol3
     *
     * @mbg.generated Sun Jul 15 12:12:25 CST 2018
     */
    public void setUsercol3(String usercol3) {
        this.usercol3 = usercol3 == null ? null : usercol3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.usercol4
     *
     * @return the value of user.usercol4
     *
     * @mbg.generated Sun Jul 15 12:12:25 CST 2018
     */
    public String getUsercol4() {
        return usercol4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.usercol4
     *
     * @param usercol4 the value for user.usercol4
     *
     * @mbg.generated Sun Jul 15 12:12:25 CST 2018
     */
    public void setUsercol4(String usercol4) {
        this.usercol4 = usercol4 == null ? null : usercol4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.usercol5
     *
     * @return the value of user.usercol5
     *
     * @mbg.generated Sun Jul 15 12:12:25 CST 2018
     */
    public String getUsercol5() {
        return usercol5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.usercol5
     *
     * @param usercol5 the value for user.usercol5
     *
     * @mbg.generated Sun Jul 15 12:12:25 CST 2018
     */
    public void setUsercol5(String usercol5) {
        this.usercol5 = usercol5 == null ? null : usercol5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.usercol6
     *
     * @return the value of user.usercol6
     *
     * @mbg.generated Sun Jul 15 12:12:25 CST 2018
     */
    public String getUsercol6() {
        return usercol6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.usercol6
     *
     * @param usercol6 the value for user.usercol6
     *
     * @mbg.generated Sun Jul 15 12:12:25 CST 2018
     */
    public void setUsercol6(String usercol6) {
        this.usercol6 = usercol6 == null ? null : usercol6.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.usercol7
     *
     * @return the value of user.usercol7
     *
     * @mbg.generated Sun Jul 15 12:12:25 CST 2018
     */
    public String getUsercol7() {
        return usercol7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.usercol7
     *
     * @param usercol7 the value for user.usercol7
     *
     * @mbg.generated Sun Jul 15 12:12:25 CST 2018
     */
    public void setUsercol7(String usercol7) {
        this.usercol7 = usercol7 == null ? null : usercol7.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.usercol8
     *
     * @return the value of user.usercol8
     *
     * @mbg.generated Sun Jul 15 12:12:25 CST 2018
     */
    public String getUsercol8() {
        return usercol8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.usercol8
     *
     * @param usercol8 the value for user.usercol8
     *
     * @mbg.generated Sun Jul 15 12:12:25 CST 2018
     */
    public void setUsercol8(String usercol8) {
        this.usercol8 = usercol8 == null ? null : usercol8.trim();
    }
}