package com.test.model;

import java.util.ArrayList;
import java.util.List;

public class UserExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbg.generated Sun Jul 15 12:12:25 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbg.generated Sun Jul 15 12:12:25 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbg.generated Sun Jul 15 12:12:25 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sun Jul 15 12:12:25 CST 2018
     */
    public UserExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sun Jul 15 12:12:25 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sun Jul 15 12:12:25 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sun Jul 15 12:12:25 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sun Jul 15 12:12:25 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sun Jul 15 12:12:25 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sun Jul 15 12:12:25 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sun Jul 15 12:12:25 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sun Jul 15 12:12:25 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sun Jul 15 12:12:25 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sun Jul 15 12:12:25 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user
     *
     * @mbg.generated Sun Jul 15 12:12:25 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUsercolIsNull() {
            addCriterion("usercol is null");
            return (Criteria) this;
        }

        public Criteria andUsercolIsNotNull() {
            addCriterion("usercol is not null");
            return (Criteria) this;
        }

        public Criteria andUsercolEqualTo(String value) {
            addCriterion("usercol =", value, "usercol");
            return (Criteria) this;
        }

        public Criteria andUsercolNotEqualTo(String value) {
            addCriterion("usercol <>", value, "usercol");
            return (Criteria) this;
        }

        public Criteria andUsercolGreaterThan(String value) {
            addCriterion("usercol >", value, "usercol");
            return (Criteria) this;
        }

        public Criteria andUsercolGreaterThanOrEqualTo(String value) {
            addCriterion("usercol >=", value, "usercol");
            return (Criteria) this;
        }

        public Criteria andUsercolLessThan(String value) {
            addCriterion("usercol <", value, "usercol");
            return (Criteria) this;
        }

        public Criteria andUsercolLessThanOrEqualTo(String value) {
            addCriterion("usercol <=", value, "usercol");
            return (Criteria) this;
        }

        public Criteria andUsercolLike(String value) {
            addCriterion("usercol like", value, "usercol");
            return (Criteria) this;
        }

        public Criteria andUsercolNotLike(String value) {
            addCriterion("usercol not like", value, "usercol");
            return (Criteria) this;
        }

        public Criteria andUsercolIn(List<String> values) {
            addCriterion("usercol in", values, "usercol");
            return (Criteria) this;
        }

        public Criteria andUsercolNotIn(List<String> values) {
            addCriterion("usercol not in", values, "usercol");
            return (Criteria) this;
        }

        public Criteria andUsercolBetween(String value1, String value2) {
            addCriterion("usercol between", value1, value2, "usercol");
            return (Criteria) this;
        }

        public Criteria andUsercolNotBetween(String value1, String value2) {
            addCriterion("usercol not between", value1, value2, "usercol");
            return (Criteria) this;
        }

        public Criteria andUsercol1IsNull() {
            addCriterion("usercol1 is null");
            return (Criteria) this;
        }

        public Criteria andUsercol1IsNotNull() {
            addCriterion("usercol1 is not null");
            return (Criteria) this;
        }

        public Criteria andUsercol1EqualTo(String value) {
            addCriterion("usercol1 =", value, "usercol1");
            return (Criteria) this;
        }

        public Criteria andUsercol1NotEqualTo(String value) {
            addCriterion("usercol1 <>", value, "usercol1");
            return (Criteria) this;
        }

        public Criteria andUsercol1GreaterThan(String value) {
            addCriterion("usercol1 >", value, "usercol1");
            return (Criteria) this;
        }

        public Criteria andUsercol1GreaterThanOrEqualTo(String value) {
            addCriterion("usercol1 >=", value, "usercol1");
            return (Criteria) this;
        }

        public Criteria andUsercol1LessThan(String value) {
            addCriterion("usercol1 <", value, "usercol1");
            return (Criteria) this;
        }

        public Criteria andUsercol1LessThanOrEqualTo(String value) {
            addCriterion("usercol1 <=", value, "usercol1");
            return (Criteria) this;
        }

        public Criteria andUsercol1Like(String value) {
            addCriterion("usercol1 like", value, "usercol1");
            return (Criteria) this;
        }

        public Criteria andUsercol1NotLike(String value) {
            addCriterion("usercol1 not like", value, "usercol1");
            return (Criteria) this;
        }

        public Criteria andUsercol1In(List<String> values) {
            addCriterion("usercol1 in", values, "usercol1");
            return (Criteria) this;
        }

        public Criteria andUsercol1NotIn(List<String> values) {
            addCriterion("usercol1 not in", values, "usercol1");
            return (Criteria) this;
        }

        public Criteria andUsercol1Between(String value1, String value2) {
            addCriterion("usercol1 between", value1, value2, "usercol1");
            return (Criteria) this;
        }

        public Criteria andUsercol1NotBetween(String value1, String value2) {
            addCriterion("usercol1 not between", value1, value2, "usercol1");
            return (Criteria) this;
        }

        public Criteria andUsercol2IsNull() {
            addCriterion("usercol2 is null");
            return (Criteria) this;
        }

        public Criteria andUsercol2IsNotNull() {
            addCriterion("usercol2 is not null");
            return (Criteria) this;
        }

        public Criteria andUsercol2EqualTo(String value) {
            addCriterion("usercol2 =", value, "usercol2");
            return (Criteria) this;
        }

        public Criteria andUsercol2NotEqualTo(String value) {
            addCriterion("usercol2 <>", value, "usercol2");
            return (Criteria) this;
        }

        public Criteria andUsercol2GreaterThan(String value) {
            addCriterion("usercol2 >", value, "usercol2");
            return (Criteria) this;
        }

        public Criteria andUsercol2GreaterThanOrEqualTo(String value) {
            addCriterion("usercol2 >=", value, "usercol2");
            return (Criteria) this;
        }

        public Criteria andUsercol2LessThan(String value) {
            addCriterion("usercol2 <", value, "usercol2");
            return (Criteria) this;
        }

        public Criteria andUsercol2LessThanOrEqualTo(String value) {
            addCriterion("usercol2 <=", value, "usercol2");
            return (Criteria) this;
        }

        public Criteria andUsercol2Like(String value) {
            addCriterion("usercol2 like", value, "usercol2");
            return (Criteria) this;
        }

        public Criteria andUsercol2NotLike(String value) {
            addCriterion("usercol2 not like", value, "usercol2");
            return (Criteria) this;
        }

        public Criteria andUsercol2In(List<String> values) {
            addCriterion("usercol2 in", values, "usercol2");
            return (Criteria) this;
        }

        public Criteria andUsercol2NotIn(List<String> values) {
            addCriterion("usercol2 not in", values, "usercol2");
            return (Criteria) this;
        }

        public Criteria andUsercol2Between(String value1, String value2) {
            addCriterion("usercol2 between", value1, value2, "usercol2");
            return (Criteria) this;
        }

        public Criteria andUsercol2NotBetween(String value1, String value2) {
            addCriterion("usercol2 not between", value1, value2, "usercol2");
            return (Criteria) this;
        }

        public Criteria andUsercol3IsNull() {
            addCriterion("usercol3 is null");
            return (Criteria) this;
        }

        public Criteria andUsercol3IsNotNull() {
            addCriterion("usercol3 is not null");
            return (Criteria) this;
        }

        public Criteria andUsercol3EqualTo(String value) {
            addCriterion("usercol3 =", value, "usercol3");
            return (Criteria) this;
        }

        public Criteria andUsercol3NotEqualTo(String value) {
            addCriterion("usercol3 <>", value, "usercol3");
            return (Criteria) this;
        }

        public Criteria andUsercol3GreaterThan(String value) {
            addCriterion("usercol3 >", value, "usercol3");
            return (Criteria) this;
        }

        public Criteria andUsercol3GreaterThanOrEqualTo(String value) {
            addCriterion("usercol3 >=", value, "usercol3");
            return (Criteria) this;
        }

        public Criteria andUsercol3LessThan(String value) {
            addCriterion("usercol3 <", value, "usercol3");
            return (Criteria) this;
        }

        public Criteria andUsercol3LessThanOrEqualTo(String value) {
            addCriterion("usercol3 <=", value, "usercol3");
            return (Criteria) this;
        }

        public Criteria andUsercol3Like(String value) {
            addCriterion("usercol3 like", value, "usercol3");
            return (Criteria) this;
        }

        public Criteria andUsercol3NotLike(String value) {
            addCriterion("usercol3 not like", value, "usercol3");
            return (Criteria) this;
        }

        public Criteria andUsercol3In(List<String> values) {
            addCriterion("usercol3 in", values, "usercol3");
            return (Criteria) this;
        }

        public Criteria andUsercol3NotIn(List<String> values) {
            addCriterion("usercol3 not in", values, "usercol3");
            return (Criteria) this;
        }

        public Criteria andUsercol3Between(String value1, String value2) {
            addCriterion("usercol3 between", value1, value2, "usercol3");
            return (Criteria) this;
        }

        public Criteria andUsercol3NotBetween(String value1, String value2) {
            addCriterion("usercol3 not between", value1, value2, "usercol3");
            return (Criteria) this;
        }

        public Criteria andUsercol4IsNull() {
            addCriterion("usercol4 is null");
            return (Criteria) this;
        }

        public Criteria andUsercol4IsNotNull() {
            addCriterion("usercol4 is not null");
            return (Criteria) this;
        }

        public Criteria andUsercol4EqualTo(String value) {
            addCriterion("usercol4 =", value, "usercol4");
            return (Criteria) this;
        }

        public Criteria andUsercol4NotEqualTo(String value) {
            addCriterion("usercol4 <>", value, "usercol4");
            return (Criteria) this;
        }

        public Criteria andUsercol4GreaterThan(String value) {
            addCriterion("usercol4 >", value, "usercol4");
            return (Criteria) this;
        }

        public Criteria andUsercol4GreaterThanOrEqualTo(String value) {
            addCriterion("usercol4 >=", value, "usercol4");
            return (Criteria) this;
        }

        public Criteria andUsercol4LessThan(String value) {
            addCriterion("usercol4 <", value, "usercol4");
            return (Criteria) this;
        }

        public Criteria andUsercol4LessThanOrEqualTo(String value) {
            addCriterion("usercol4 <=", value, "usercol4");
            return (Criteria) this;
        }

        public Criteria andUsercol4Like(String value) {
            addCriterion("usercol4 like", value, "usercol4");
            return (Criteria) this;
        }

        public Criteria andUsercol4NotLike(String value) {
            addCriterion("usercol4 not like", value, "usercol4");
            return (Criteria) this;
        }

        public Criteria andUsercol4In(List<String> values) {
            addCriterion("usercol4 in", values, "usercol4");
            return (Criteria) this;
        }

        public Criteria andUsercol4NotIn(List<String> values) {
            addCriterion("usercol4 not in", values, "usercol4");
            return (Criteria) this;
        }

        public Criteria andUsercol4Between(String value1, String value2) {
            addCriterion("usercol4 between", value1, value2, "usercol4");
            return (Criteria) this;
        }

        public Criteria andUsercol4NotBetween(String value1, String value2) {
            addCriterion("usercol4 not between", value1, value2, "usercol4");
            return (Criteria) this;
        }

        public Criteria andUsercol5IsNull() {
            addCriterion("usercol5 is null");
            return (Criteria) this;
        }

        public Criteria andUsercol5IsNotNull() {
            addCriterion("usercol5 is not null");
            return (Criteria) this;
        }

        public Criteria andUsercol5EqualTo(String value) {
            addCriterion("usercol5 =", value, "usercol5");
            return (Criteria) this;
        }

        public Criteria andUsercol5NotEqualTo(String value) {
            addCriterion("usercol5 <>", value, "usercol5");
            return (Criteria) this;
        }

        public Criteria andUsercol5GreaterThan(String value) {
            addCriterion("usercol5 >", value, "usercol5");
            return (Criteria) this;
        }

        public Criteria andUsercol5GreaterThanOrEqualTo(String value) {
            addCriterion("usercol5 >=", value, "usercol5");
            return (Criteria) this;
        }

        public Criteria andUsercol5LessThan(String value) {
            addCriterion("usercol5 <", value, "usercol5");
            return (Criteria) this;
        }

        public Criteria andUsercol5LessThanOrEqualTo(String value) {
            addCriterion("usercol5 <=", value, "usercol5");
            return (Criteria) this;
        }

        public Criteria andUsercol5Like(String value) {
            addCriterion("usercol5 like", value, "usercol5");
            return (Criteria) this;
        }

        public Criteria andUsercol5NotLike(String value) {
            addCriterion("usercol5 not like", value, "usercol5");
            return (Criteria) this;
        }

        public Criteria andUsercol5In(List<String> values) {
            addCriterion("usercol5 in", values, "usercol5");
            return (Criteria) this;
        }

        public Criteria andUsercol5NotIn(List<String> values) {
            addCriterion("usercol5 not in", values, "usercol5");
            return (Criteria) this;
        }

        public Criteria andUsercol5Between(String value1, String value2) {
            addCriterion("usercol5 between", value1, value2, "usercol5");
            return (Criteria) this;
        }

        public Criteria andUsercol5NotBetween(String value1, String value2) {
            addCriterion("usercol5 not between", value1, value2, "usercol5");
            return (Criteria) this;
        }

        public Criteria andUsercol6IsNull() {
            addCriterion("usercol6 is null");
            return (Criteria) this;
        }

        public Criteria andUsercol6IsNotNull() {
            addCriterion("usercol6 is not null");
            return (Criteria) this;
        }

        public Criteria andUsercol6EqualTo(String value) {
            addCriterion("usercol6 =", value, "usercol6");
            return (Criteria) this;
        }

        public Criteria andUsercol6NotEqualTo(String value) {
            addCriterion("usercol6 <>", value, "usercol6");
            return (Criteria) this;
        }

        public Criteria andUsercol6GreaterThan(String value) {
            addCriterion("usercol6 >", value, "usercol6");
            return (Criteria) this;
        }

        public Criteria andUsercol6GreaterThanOrEqualTo(String value) {
            addCriterion("usercol6 >=", value, "usercol6");
            return (Criteria) this;
        }

        public Criteria andUsercol6LessThan(String value) {
            addCriterion("usercol6 <", value, "usercol6");
            return (Criteria) this;
        }

        public Criteria andUsercol6LessThanOrEqualTo(String value) {
            addCriterion("usercol6 <=", value, "usercol6");
            return (Criteria) this;
        }

        public Criteria andUsercol6Like(String value) {
            addCriterion("usercol6 like", value, "usercol6");
            return (Criteria) this;
        }

        public Criteria andUsercol6NotLike(String value) {
            addCriterion("usercol6 not like", value, "usercol6");
            return (Criteria) this;
        }

        public Criteria andUsercol6In(List<String> values) {
            addCriterion("usercol6 in", values, "usercol6");
            return (Criteria) this;
        }

        public Criteria andUsercol6NotIn(List<String> values) {
            addCriterion("usercol6 not in", values, "usercol6");
            return (Criteria) this;
        }

        public Criteria andUsercol6Between(String value1, String value2) {
            addCriterion("usercol6 between", value1, value2, "usercol6");
            return (Criteria) this;
        }

        public Criteria andUsercol6NotBetween(String value1, String value2) {
            addCriterion("usercol6 not between", value1, value2, "usercol6");
            return (Criteria) this;
        }

        public Criteria andUsercol7IsNull() {
            addCriterion("usercol7 is null");
            return (Criteria) this;
        }

        public Criteria andUsercol7IsNotNull() {
            addCriterion("usercol7 is not null");
            return (Criteria) this;
        }

        public Criteria andUsercol7EqualTo(String value) {
            addCriterion("usercol7 =", value, "usercol7");
            return (Criteria) this;
        }

        public Criteria andUsercol7NotEqualTo(String value) {
            addCriterion("usercol7 <>", value, "usercol7");
            return (Criteria) this;
        }

        public Criteria andUsercol7GreaterThan(String value) {
            addCriterion("usercol7 >", value, "usercol7");
            return (Criteria) this;
        }

        public Criteria andUsercol7GreaterThanOrEqualTo(String value) {
            addCriterion("usercol7 >=", value, "usercol7");
            return (Criteria) this;
        }

        public Criteria andUsercol7LessThan(String value) {
            addCriterion("usercol7 <", value, "usercol7");
            return (Criteria) this;
        }

        public Criteria andUsercol7LessThanOrEqualTo(String value) {
            addCriterion("usercol7 <=", value, "usercol7");
            return (Criteria) this;
        }

        public Criteria andUsercol7Like(String value) {
            addCriterion("usercol7 like", value, "usercol7");
            return (Criteria) this;
        }

        public Criteria andUsercol7NotLike(String value) {
            addCriterion("usercol7 not like", value, "usercol7");
            return (Criteria) this;
        }

        public Criteria andUsercol7In(List<String> values) {
            addCriterion("usercol7 in", values, "usercol7");
            return (Criteria) this;
        }

        public Criteria andUsercol7NotIn(List<String> values) {
            addCriterion("usercol7 not in", values, "usercol7");
            return (Criteria) this;
        }

        public Criteria andUsercol7Between(String value1, String value2) {
            addCriterion("usercol7 between", value1, value2, "usercol7");
            return (Criteria) this;
        }

        public Criteria andUsercol7NotBetween(String value1, String value2) {
            addCriterion("usercol7 not between", value1, value2, "usercol7");
            return (Criteria) this;
        }

        public Criteria andUsercol8IsNull() {
            addCriterion("usercol8 is null");
            return (Criteria) this;
        }

        public Criteria andUsercol8IsNotNull() {
            addCriterion("usercol8 is not null");
            return (Criteria) this;
        }

        public Criteria andUsercol8EqualTo(String value) {
            addCriterion("usercol8 =", value, "usercol8");
            return (Criteria) this;
        }

        public Criteria andUsercol8NotEqualTo(String value) {
            addCriterion("usercol8 <>", value, "usercol8");
            return (Criteria) this;
        }

        public Criteria andUsercol8GreaterThan(String value) {
            addCriterion("usercol8 >", value, "usercol8");
            return (Criteria) this;
        }

        public Criteria andUsercol8GreaterThanOrEqualTo(String value) {
            addCriterion("usercol8 >=", value, "usercol8");
            return (Criteria) this;
        }

        public Criteria andUsercol8LessThan(String value) {
            addCriterion("usercol8 <", value, "usercol8");
            return (Criteria) this;
        }

        public Criteria andUsercol8LessThanOrEqualTo(String value) {
            addCriterion("usercol8 <=", value, "usercol8");
            return (Criteria) this;
        }

        public Criteria andUsercol8Like(String value) {
            addCriterion("usercol8 like", value, "usercol8");
            return (Criteria) this;
        }

        public Criteria andUsercol8NotLike(String value) {
            addCriterion("usercol8 not like", value, "usercol8");
            return (Criteria) this;
        }

        public Criteria andUsercol8In(List<String> values) {
            addCriterion("usercol8 in", values, "usercol8");
            return (Criteria) this;
        }

        public Criteria andUsercol8NotIn(List<String> values) {
            addCriterion("usercol8 not in", values, "usercol8");
            return (Criteria) this;
        }

        public Criteria andUsercol8Between(String value1, String value2) {
            addCriterion("usercol8 between", value1, value2, "usercol8");
            return (Criteria) this;
        }

        public Criteria andUsercol8NotBetween(String value1, String value2) {
            addCriterion("usercol8 not between", value1, value2, "usercol8");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user
     *
     * @mbg.generated do_not_delete_during_merge Sun Jul 15 12:12:25 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user
     *
     * @mbg.generated Sun Jul 15 12:12:25 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}