package com.test.dao;

import com.test.model.Test;
import com.test.model.TestExample;
import com.tnative.base.dao.BaseMapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TestMapper extends BaseMapper<Test> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbg.generated Sun Jul 15 12:12:25 CST 2018
     */
    long countByExample(TestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbg.generated Sun Jul 15 12:12:25 CST 2018
     */
    int deleteByExample(TestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbg.generated Sun Jul 15 12:12:25 CST 2018
     */
    List<Test> selectByExample(TestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbg.generated Sun Jul 15 12:12:25 CST 2018
     */
    int updateByExampleSelective(@Param("record") Test record, @Param("example") TestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbg.generated Sun Jul 15 12:12:25 CST 2018
     */
    int updateByExample(@Param("record") Test record, @Param("example") TestExample example);

}