package com.tnative.base.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.test.model.Test;
import com.test.model.TestExample;
import com.tnative.base.request.BasePage;


public interface BaseMapper<T> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbg.generated Sat Jul 14 22:46:25 CST 2018
     */
    int deleteByPrimaryKey(Integer idtest);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbg.generated Sat Jul 14 22:46:25 CST 2018
     */
    int insert(T record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbg.generated Sat Jul 14 22:46:25 CST 2018
     */
    int insertSelective(T record);

   

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbg.generated Sat Jul 14 22:46:25 CST 2018
     */
    T selectByPrimaryKey(Integer idtest);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbg.generated Sat Jul 14 22:46:25 CST 2018
     */
    int updateByPrimaryKeySelective(T record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbg.generated Sat Jul 14 22:46:25 CST 2018
     */
    int updateByPrimaryKey(T record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbg.generated Sat Jul 14 22:46:25 CST 2018
     */
    List<T> selectAll(T record);

}